name: Pre-commit checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update-readme-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Update README version
      run: |
        cat > update_version.py << 'EOF'
        import re

        def update_readme_version():
            # Get version from version.py
            with open('version.py', 'r', encoding='utf-8') as f:
                version_content = f.read()
            
            version_match = re.search(r'__version__\s*=\s*[\'"]([^\'"]*)[\'"]', version_content)
            if not version_match:
                print('Warning: Could not find version in version.py')
                return
            
            version = version_match.group(1)
            
            # Update README.md
            try:
                with open('README.md', 'r', encoding='utf-8') as f:
                    readme_content = f.read()
            except UnicodeDecodeError:
                with open('README.md', 'r', encoding='latin-1') as f:
                    readme_content = f.read()
            
            updated_readme = re.sub(
                r'(\*\*Version:\*\*\s*`)v[^`]*(`.*)',
                f'\\1v{version}\\2',
                readme_content
            )
            
            with open('README.md', 'w', encoding='utf-8') as f:
                f.write(updated_readme)
            
            print(f'Updated README.md with version v{version}')

        update_readme_version()
        EOF
        python update_version.py
    
    - name: Commit changes if any
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "docs: Update README.md version [skip ci]"
        git push origin HEAD:${GITHUB_REF#refs/heads/} 