name: Pre-commit checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  pre-commit-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.3'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install black pylint pytest
    
    - name: Code formatting check (Black)
      run: |
        black --check --diff .
      continue-on-error: true
    
    - name: Linting check (Pylint)
      run: |
        find . -name "*.py" -not -path "./.venv/*" -not -path "./venv/*" | xargs pylint --disable=C0114,C0115,C0116
      continue-on-error: true
    
    - name: Run tests
      run: |
        pytest 